### ISSUE TITLE
Crash on entering the layout editor after upgrading to v1.2.0

### ISSUE THREAD

**Issue by githubtefo** [experiment322/controlloid-client#10]
Hi!
I've been using Controlloid on my Lineage OS mido.
But since the last update downloaded from F-droid, the App crashes every time I open the a layout to edit/create it.

**Comment by experiment322** [comment]
Even if you create a new layout and try to edit it?
Or does this happen only on existing layouts?

**Comment by githubtefo** [comment]
It happens on both, new and old layouts.

**Comment by hpmc13** [comment]
I'm seeing the same result as well. Existing layouts, new layouts, even if I change the theme. 
Thanks for looking into this. I really like this app.

**Comment by githubtefo** [comment]
> Thanks for looking into this. I really like this app.

Me too! I really appreciate it.

**Comment by experiment322** [comment]
I think I've found the culprit and it's because of the way I store the current theme (💀*bad architectural decisions* 💀). The issue only appears when you've upgraded the app from a previous version to v1.2.0. It doesn't happen on a clean install.

So, a quick fix for you guys would be to `reset the preferences`, thus resetting the theme and then you can set them back as they were.

I'll try to release a new version these days to fix the issue.

**Comment by hpmc13** [comment]
Thank You! Resetting worked perfectly.

**Comment by githubtefo** [comment]
Thank you! It's working here too! and I can clearly notice that the dark theme switch from grey to dark.
