### ISSUE TITLE
There is no CONNECT or IP button

### ISSUE THREAD

**Issue by gerroon** [experiment322/controlloid-client#12]
Hi
I am using the Fdroid build on LineageOS 14.1 and I see no buttons or anything in the Controller menu. 

The help in the home page says open the controller and press CONNECT. The onlything I see inn the controller page is `select layout`

**Comment by experiment322** [comment]
Hello, @gerroon.

That happens because you haven't created any layouts yet.
To do so, you need to go to the layouts screen, input a name, press enter and then tap on the new entry in the list (the new layout you've created) to edit it.
Once you tap it, you'll be presented with the layout editor (a black screen) where you press on the black area to add new buttons. Once you've added the necessary buttons you need to press back to save the layout.
Once saved, you'll see again the list of the layouts and you need to press the star next to it to set it as active.
Then, you can go back and connect to the server.

Hope it's clear enough 😄.

**Comment by gerroon** [comment]
Thanks for the reply.

I actually created a layout. That does not seem to be the issue. The connect button did not show up until pressing the star, so that was the trick, maybe there could be a way to make that obvious?

**Comment by experiment322** [comment]
Yeah, I know. The UX isn't so nice 😅.

Maybe I can add a more explicit description on that screen if you didn't star a layout that states that you need to star it, or something like that.

I'll be thinking about it, but for the time being, I'll close the issue.
